##' Extract hazard ratio and confidence intervals from a coxph object
##'
##' This convenience function extracts hazard ratio and confidence intervals from a coxph object,
##' as generated by a call to coxph(), comparing survival times between two groups.
##'
##' @param coxphData coxph object; example usage:
##' \dontrun{
##' library(survival)
##' # Create example data
##' set.seed(123)
##' df <- data.frame(
##'   TTE = rexp(200, rate = 0.1),  # Time to event data
##'   Cens = rbinom(200, size = 1, prob = 0.7),  # Censoring information
##'   group = sample(c("Treatment", "Control"), 200, replace = TRUE)  # Group information
##' )
##' # Fit Cox proportional hazards model
##' coxphData <- coxph(Surv(TTE, Cens) ~ group, data = df)
##' # Extract HR and CI
##' results <- getHRandCIfromCoxph(coxphData)
##' print(results)
##' }
##'
##' @author Dorothee Nickles
##' @author Dongqiang Zeng
##' @export
##' @import survival
getHRandCIfromCoxph <- function(coxphData) {
  # Check if coxphData is a valid coxph object
  stopifnot(is(coxphData, "coxph"))

  # Extract coefficients and confidence intervals
  summary_data <- summary(coxphData)
  coef_data <- summary_data$coefficients
  conf_int <- summary_data$conf.int

  # Prepare the output
  results <- data.frame(
    P = coef_data[, "Pr(>|z|)"],
    HR = exp(coef_data[, "coef"]),
    CI_low = exp(conf_int[, "lower .95"]),
    CI_high = exp(conf_int[, "upper .95"])
  )

  # Round the results for better readability
  results$HR <- round(results$HR, 4)
  results$CI_low <- round(results$CI_low, 4)
  results$CI_high <- round(results$CI_high, 4)
  results$P <- round(results$P, 4)

  return(results)
}
